= Chord Dictionary
Guilherme I F L Weizenmann
2023-11-10
:jbake-type: page


++++
<div class="container m-3 p-3">
    <form class="columns">
        <fieldset class="column box">
            <legend class="title is-4 mb-2">Instrumento</legend>
            <div class="columns">
                <label class="column">
                    <input type="radio" checked name="tuning" value="guitar.standard" />
                    Violão/Guitarra
                </label>
                <label class="column">
                    <input type="radio" name="tuning" value="ukulele.standard"/>
                    Ukulele
                </label>
                <label class="column">
                    <input type="radio" name="tuning" value="bass.standard"/>
                    Baixo
                </label>
            </div>
        </fieldset>
        <fieldset class="column box">
            <legend class="title is-4 mb-2">Acorde</legend>
            <div class="columns">
                <label class="column is-two-thirds">
                    Nome do acorde:
                    <input type="text" id="chord-name" />
                </label>
                <div class="column is-one-third">
                    <button class="button" type="button" onclick="showChords()">Visualizar</button>
                </div>
            </div>
        </fieldset>
    </form>
    <div id="chords-list">
    </div>
</div>

<script>
function showChords() {
    document.querySelector('#chords-list').innerHTML = '';

    const name = document.querySelector('#chord-name').value;

    const instrumentTuning = [...document.querySelectorAll('*[name="tuning"]')].filter(el => el.checked)[0].value.split('.');

    let tuning = chordictionary.tuning;
    for (const insTun of instrumentTuning) {
        tuning = tuning[insTun];
    }

    const instrument = new chordictionary.Instrument(tuning.join(''), 12, 5, 4);
    let tabs = instrument.getChordsList(name).chordList;

    //console.log(tabs)
    
    tabs.sort((a, b) => {
        let ax = a.tab.filter(f => f == "x").length;
        let bx = b.tab.filter(f => f == "x").length;
        const byXCount = ax > bx ? 1 : (ax < bx ? -1 : 0);
        ax = a.tab.map((el, idx) => el == "x" ? idx : 0).reduce((p, c) => p + c);
        bx = b.tab.map((el, idx) => el == "x" ? idx : 0).reduce((p, c) => p + c);
        const byXCountAndXString = byXCount != 0 ? byXCount : (ax > bx ? 1 : (ax < bx ? -1: 0));
        ax = a.tab.map((el, idx) => el == "x" ? idx : el).reduce((p, c) => p + c);
        bx = b.tab.map((el, idx) => el == "x" ? idx : el).reduce((p, c) => p + c);
        const byXCountAndXStringAndHandProcimity = byXCountAndXString != 0 ? byXCountAndXString : (ax > bx ? 1 : (ax < bx ? -1: 0));
        return byXCountAndXStringAndHandProcimity;
    });
    
    tabs = tabs.filter( tab => {
        const freqs = tab.tab.reduce(function (acc, curr) {
            return acc[curr] ? ++acc[curr] : acc[curr] = 1, acc;
        }, {0: 0, x: 0});
        // probably impossible bars
        if (freqs[1] > 2 && freqs[0] > 0 && (freqs["x"] == 0 || tab.tab[0] != "x")) {
            return false;
        }
        if (freqs[0] == 0 && freqs[1] >= 2) {
            return true;
        }
        if (tab.tab.filter(f => f != "x" && f != 0).length <= 4) {
            return true;
        }
        return false;
    });
    tabs.forEach(tab => {
        tab.info = instrument.getChordInfo(tab).first();
    });
    if (instrumentTuning[0] == 'guitar') {
        tabs.sort((a, b) => {
            if (a.info.name == b.info.name) {
                return 0;
            }
            if (a.info.name == name) {
                return -1;
            }
            if (b.info.name == name) {
                return 1;
            }
            if (a.info.name.startsWith(name)) {
                return -1;
            }
            if (b.info.name.startsWith(name)) {
                return 1;
            }
            return a.info.name.localeCompare(b.info.name);
        });
    }
    if (tabs?.length > 0) {
        let diagrams = '';
        tabs.forEach(tab => {
            diagrams += '<div class="m-1 p-1" style="display: inline-block">' + instrument.getChordLayout(tab.tab, tab.info) + '</div>';
        });
        document.querySelector('#chords-list').innerHTML = diagrams;
    }

}
</script>
++++