#!/usr/bin/env bash
set -euo pipefail
#set -x

declare -A tags=()

features=$(grep ' = r"' ../../src/chords/text_formatting.py | tr -d ' ')


##########################################
# INIT
##########################################
echo "=== Getting tags and chars..."
for class in $features; do
  echo "Class: $class"

  tag="${class%%=r*}"
  tag="${tag,,}"
  echo "Tag: $tag"

  char=${class##*=r}
  char=${char: -2:1}
  echo "Char $char"

  tags[$tag]=$char
done


##########################################
# TAGS
##########################################
echo "=== Generating test files by tag"
for tag in "${!tags[@]}"; do
  echo
  char=${tags[$tag]}
  echo "${tag}: ${char}"
  echo

  echo "${char}content inside single symbols${char}
${char}${char}can have ${char} inside as long we don't use another one inside${char}${char}
${char}${char} without matching close has no effect

file\\${char}name\\${char}with\\${char}underscores
${char}${char}file\\${char}name\\${char}with\\${char}underscores${char}${char}
any other ${char}one line${char} can be used ${char}naturally${char} like this
" | tee "${tag}.md"

  echo "<p><${tag}>content inside single symbols</${tag}>
<${tag}>can have ${char} inside as long we don't use another one inside</${tag}>
${char}${char} without matching close has no effect</p>
<p>file${char}name${char}with${char}underscores
<${tag}>file${char}name${char}with${char}underscores</${tag}>
any other <${tag}>one line</${tag}> can be used <${tag}>naturally</${tag}> like this</p>
" | tee "${tag}.html"
done


##########################################
# MODES
##########################################
function for_mode() {
  local mode=$1

  output_md="mode-${mode}.md"
  output_html="mode-${mode}.html"

  echo "options: { 'mode': '${mode}' }" | tee $output_md
  echo -n "<p>" | tee $output_html

  first_line=true
  for tag in "${!tags[@]}"; do
    if [ $first_line == true ]; then
      first_line=false
    else
      echo | tee -a $output_html
    fi

    local char=${tags[$tag]}
    local start_tag="<$tag>"
    local end_tag="</$tag>"

    case $mode in
      single)
        single_start="$start_tag"
        single_end="$end_tag"
        single_and_word_start="$single_start"
        single_and_word_end="$single_end"
        double_start="$char$char"
        double_end="$double_start"
        ;;
      double)
        single_start="$char"
        single_end="$char"
        single_and_word_start="$char"
        single_and_word_end="$char"
        double_start="$start_tag"
        double_end="$end_tag"
        ;;
      word)
        single_start="$char"
        single_end="$char"
        single_and_word_start="$start_tag"
        single_and_word_end="$end_tag"
        double_start="$char$char"
        double_end="$char$char"
        ;;
    esac

    echo "${tag}: ${char}"
    echo "${char}${char}here we can use ${char} after ${char} with ease, but can be for ${char}words${char} only${char}${char}" | tee -a $output_md
    echo -n "${double_start}here we can use ${single_start} after ${single_end} with ease, but can be for ${single_and_word_start}words${single_and_word_end} only${double_end}" | tee -a $output_html
  done

  echo "</p>" | tee -a $output_html
}

for_mode single
for_mode double
for_mode word


##########################################
# HELP
##########################################
(
  echo
  echo "# Text Formatting Extensions"
  echo
  echo '!!! danger "Attention"'
  echo
  echo '    Default strong/em from python markdown are disabled by this extension'
  echo
  for tag in "${!tags[@]}"; do
    char=${tags[$tag]}
    echo "${tag}: ${char}"
    echo ":   you can use single or double ${char} to create an ${tag} tag"
    echo ":   single mode (${char}) cannot have the char ${char} inside"
    echo ":   double mode (${char}${char}) can have single ${char} inside"
    echo ":   word mode cannot have single ${char} inside nor space"
    echo
  done

  echo
  echo "> generated by $0"
) | tee ../../README_text_formatting.md
echo Done
